services:

  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - list-manager-network

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: list_manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - list-manager-network

volumes:
  postgres_data:
    driver: local

networks:
  list-manager-network:
    driver: bridge
